"""
Django settings for parliment project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

from pathlib import Path
import os
import warnings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-this-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',  # Your main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parliment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parliment.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Changed to Indian timezone

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================
# SUPPRESS WARNINGS (Optional - remove in production)
# =============================================

# Suppress the specific warning about database access during app initialization
# These warnings are not harmful but can be noisy during development
if DEBUG:
    warnings.filterwarnings(
        'ignore',
        'Accessing the database during app initialization is discouraged',
        RuntimeWarning,
        'django.db.backends.utils'
    )

# =============================================
# LOGGING CONFIGURATION
# =============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tracker': {  # Your app's logger
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# =============================================
# CUSTOM SETTINGS FOR YOUR APPLICATION
# =============================================

# Scraping settings
SCRAPING_INTERVAL_HOURS = 24  # How often to scrape by default
SCRAPING_TIMEOUT_SECONDS = 30  # Timeout for scraping requests

# API settings
API_RATE_LIMIT = '100/hour'  # Rate limiting for API endpoints

# Cache settings (optional - uncomment if you want to use caching)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

# =============================================
# SECURITY SETTINGS (FOR PRODUCTION)
# =============================================
# Uncomment and configure these when deploying to production

# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# =============================================
# END OF SETTINGS
# =============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',  # This should be here
]
# Scraping configuration
SCRAPING_CONFIG = {
    'DEFAULT_SOURCE': 'all',
    'TIMEOUT': 30,
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 5,
    'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) ParliamentTracker/1.0',
    'MAX_RECORDS_PER_JOB': 1000,
    'ENABLE_LOGGING': True,
    'LOG_LEVEL': 'INFO',
}

# =============================================
# SCRAPING URL CONFIGURATION
# =============================================

# PRS India (PRS Legislative Research) URLs
PRS_INDIA_URL = 'https://prsindia.org/bill-tracker'
PRS_BILLS_API = 'https://prsindia.org/api/bills'
PRS_BILL_DETAIL_URL = 'https://prsindia.org/bill-tracker/bill-details'

# Lok Sabha URLs
LOKSABHA_URL = 'https://loksabha.nic.in/bills'
LOKSABHA_API = 'https://loksabha.nic.in/api/bills'
LOKSABHA_BILL_DETAIL_URL = 'https://loksabha.nic.in/bills/bill-details'

# Rajya Sabha URLs
RAJYASABHA_URL = 'https://rajyasabha.nic.in/bills'
RAJYASABHA_API = 'https://rajyasabha.nic.in/api/bills'
RAJYASABHA_BILL_DETAIL_URL = 'https://rajyasabha.nic.in/bills/bill-details'

# Scraping Configuration
SCRAPING_CONFIG = {
    'DEFAULT_SOURCE': 'all',
    'TIMEOUT': 30,
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 5,
    'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ParliamentTracker/1.0',
    'MAX_RECORDS_PER_JOB': 1000,
    'ENABLE_LOGGING': True,
    'LOG_LEVEL': 'INFO',
    'PRS_INDIA_URL': 'https://prsindia.org/bill-tracker',
    'LOKSABHA_URL': 'https://loksabha.nic.in/bills',
    'RAJYASABHA_URL': 'https://rajyasabha.nic.in/bills',
}

# =============================================
# SCRAPING URL CONFIGURATION
# =============================================

# PRS India (PRS Legislative Research) URLs
PRS_INDIA_URL = 'https://prsindia.org/bill-tracker'
PRS_BILLS_API = 'https://prsindia.org/api/bills'
PRS_BILL_DETAIL_URL = 'https://prsindia.org/bill-tracker/bill-details'

# Lok Sabha URLs (Note: Different possible naming conventions)
LOK_SABHA_URL = 'https://loksabha.nic.in/bills'
LOKSABHA_URL = 'https://loksabha.nic.in/bills'
LOK_SABHA_API = 'https://loksabha.nic.in/api/bills'
LOKSABHA_API = 'https://loksabha.nic.in/api/bills'
LOK_SABHA_BILL_DETAIL_URL = 'https://loksabha.nic.in/bills/bill-details'
LOKSABHA_BILL_DETAIL_URL = 'https://loksabha.nic.in/bills/bill-details'

# Rajya Sabha URLs
RAJYA_SABHA_URL = 'https://rajyasabha.nic.in/bills'
RAJYASABHA_URL = 'https://rajyasabha.nic.in/bills'
RAJYA_SABHA_API = 'https://rajyasabha.nic.in/api/bills'
RAJYASABHA_API = 'https://rajyasabha.nic.in/api/bills'
RAJYA_SABHA_BILL_DETAIL_URL = 'https://rajyasabha.nic.in/bills/bill-details'
RAJYASABHA_BILL_DETAIL_URL = 'https://rajyasabha.nic.in/bills/bill-details'

# Scraping Configuration
SCRAPING_CONFIG = {
    'DEFAULT_SOURCE': 'all',
    'TIMEOUT': 30,
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 5,
    'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ParliamentTracker/1.0',
    'MAX_RECORDS_PER_JOB': 1000,
    'ENABLE_LOGGING': True,
    'LOG_LEVEL': 'INFO',
    
    # URLs with both naming conventions to be safe
    'PRS_INDIA_URL': 'https://prsindia.org/bill-tracker',
    'LOK_SABHA_URL': 'https://loksabha.nic.in/bills',
    'LOKSABHA_URL': 'https://loksabha.nic.in/bills',
    'RAJYA_SABHA_URL': 'https://rajyasabha.nic.in/bills',
    'RAJYASABHA_URL': 'https://rajyasabha.nic.in/bills',
}
# parliament/settings.py - add these lines

# Scraping URLs
PRS_INDIA_URL = 'https://prsindia.org/bill-tracker'
LOK_SABHA_URL = 'https://loksabha.nic.in/bills'
RAJYA_SABHA_URL = 'https://rajyasabha.nic.in/bills'

# Celery settings for real-time scraping
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULE = {
    'scrape-all-sources': {
        'task': 'bills.views.scrape_all_sources',
        'schedule': 3600.0,  # Every hour
    },
}
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',  # This should be here
]
# Add these to settings.py

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

CELERY_BEAT_SCHEDULE = {
    'scrape-prs-daily': {
        'task': 'tracker.scraper.scrape_prs',
        'schedule': 3600.0,  # Every hour
    },
    'scrape-loksabha-daily': {
        'task': 'tracker.scraper.scrape_loksabha',
        'schedule': 7200.0,  # Every 2 hours
    },
    'scrape-rajyasabha-daily': {
        'task': 'tracker.scraper.scrape_rajyasabha',
        'schedule': 7200.0,  # Every 2 hours
    },
    'scrape-all-sources': {
        'task': 'tracker.scraper.scrape_all_sources',
        'schedule': 3600.0,  # Every hour
    },
}

# Scraping URLs
PRS_INDIA_URL = 'https://prsindia.org/bill-tracker'
LOK_SABHA_URL = 'https://loksabha.nic.in/bills'
RAJYA_SABHA_URL = 'https://rajyasabha.nic.in/bills'