# Generated by Django 4.2.7 on 2026-02-24 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(help_text='Unique bill identifier', max_length=50, unique=True)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('house', models.CharField(choices=[('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha'), ('BOTH', 'Both Houses')], default='LOK_SABHA', max_length=20)),
                ('introduced_in', models.CharField(blank=True, max_length=50)),
                ('introduction_date', models.DateField(blank=True, null=True)),
                ('passed_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('LAPSED', 'Lapsed')], default='PENDING', max_length=20)),
                ('status_details', models.TextField(blank=True)),
                ('introduced_by', models.CharField(blank=True, max_length=500)),
                ('introduced_by_mp', models.CharField(blank=True, max_length=200)),
                ('introduced_by_party', models.CharField(blank=True, max_length=100)),
                ('ministry', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('prs_link', models.URLField(blank=True, max_length=500)),
                ('loksabha_link', models.URLField(blank=True, max_length=500)),
                ('rajyasabha_link', models.URLField(blank=True, max_length=500)),
                ('pdf_link', models.URLField(blank=True, max_length=500)),
                ('source', models.CharField(default='PRS', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-introduction_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('PRS', 'PRS India'), ('LOK_SABHA', 'Lok Sabha'), ('RAJYA_SABHA', 'Rajya Sabha')], max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('scrape_frequency', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='BillUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracker.bill')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_id'], name='tracker_bil_bill_id_501e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['house'], name='tracker_bil_house_85bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='tracker_bil_status_c3dd78_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['introduction_date'], name='tracker_bil_introdu_956aa9_idx'),
        ),
    ]
