# Generated by Django 4.2.7 on 2026-02-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['state'], name='tracker_bil_state_d8ee96_idx'),
        ),
    ]
